### ISSUE TITLE
Make better HazDroneCorp icon

### ISSUE THREAD

**Issue by HazmatDrone** [HazmatDrone/HazmatDrone#1]
@GlaucaBlitz could you do something for this? Something similar to the [existing HazDroneCorp icon](https://github.com/HazDroneCorp), but more refined

**Comment by GlaucaBlitz** [comment]
![HazDroneCorp](https://user-images.githubusercontent.com/73702239/101748443-86f5d600-3b07-11eb-8555-427e97b2e68e.png)

**Comment by HazmatDrone** [comment]
Approved.
